const express=require('express'),session=require('express-session'),helmet=require('helmet'),crypto=require('crypto'),path=require('path');
const db=require('./db'),s=require('./service'),v=require('./validation'),bot=require('./bot'),nitrado=require('./nitrado'),vault=require('./crypto'),Store=require('./session'),premium=require('./premium'),fileValidator=require('./file-validator'),modules=require('./modules');
const {fail}=require('./errors');
const asyncRoute=fn=>(req,res,next)=>Promise.resolve().then(()=>fn(req,res,next)).catch(next);
const safeConfig=c=>{const {nitrado_token_enc,webhook_secret_hash,...safe}=c;return {...safe,nitradoConnected:Boolean(nitrado_token_enc),webhookReady:Boolean(webhook_secret_hash)}};
function verifyDiscordBridgeToken(token){
 const secret=String(process.env.DISCORD_BRIDGE_SECRET||'');if(secret.length<32)fail('discordError',503);
 const parts=String(token||'').split('.');if(parts.length!==2)fail('unauthorized',401);const [payload,sig]=parts;
 const expected=crypto.createHmac('sha256',secret).update(payload).digest('base64url'),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))fail('unauthorized',401);
 let data;try{data=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'))}catch{fail('unauthorized',401)}
 if(data?.v!==1||!data?.user?.id||!Array.isArray(data.guilds)||Number(data.exp)<Date.now())fail('expiredLink',401);
 data.guilds=data.guilds.filter(g=>/^\d{15,22}$/.test(String(g.id||''))).slice(0,100).map(g=>({id:String(g.id),name:String(g.name||g.id).slice(0,100),icon:g.icon?'https://cdn.discordapp.com/icons/'+g.id+'/'+g.icon+'.webp?size=128':null,owner:Boolean(g.owner),permissions:String(g.permissions||'0'),installed:false,memberCount:0,role:'admin'}));
 return data;
}
function app(){
 const app=express();app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'6mb'}));
 app.use(session({secret:process.env.SESSION_SECRET,store:new Store(),resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:365*86400000}}));
 app.use((req,res,next)=>{const shared=req.path.startsWith('/api/top-servers');if(req.path.startsWith('/api/'))res.set('Cache-Control','no-store');if(shared){res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.set('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.sendStatus(204)}if(!shared&&['POST','PATCH','PUT','DELETE'].includes(req.method)&&req.headers.origin){try{if(new URL(req.headers.origin).host!==req.get('host'))fail('forbidden',403)}catch(e){return next(e)}}next()});
 const route=(method,url,...handlers)=>app[method](url,...handlers.map(asyncRoute));
 const login=async(req,res,next)=>{if(!req.session.user)fail('unauthorized',401);if(req.session.role!=='owner'&&Date.now()-(req.session.checkedAt||0)>300000){await bot.verify(req.session.guildId,req.session.user,req.session.role);req.session.checkedAt=Date.now()}next()};
 const staff=(req,res,next)=>{if(!['owner','admin'].includes(req.session.role))fail('forbidden',403);next()};
 const owner=(req,res,next)=>{if(req.session.role!=='owner')fail('forbidden',403);next()};
 const scope=(req,res,next)=>{const g=String(req.query.guild||req.body.guild||req.session.guildId||'');if(!g)fail('selectGuild');req.g=g;next()};
 const actor=req=>req.session.user;
 const attemptMap=new Map();function limit(req){const now=Date.now();const key=req.ip;let item=attemptMap.get(key);if(!item||now-item.at>900000)item={at:now,n:0};item.n++;attemptMap.set(key,item);if(item.n>12)fail('rateLimit',429);if(attemptMap.size>2000)for(const [key,item]of attemptMap)if(now-item.at>900000)attemptMap.delete(key)}
 const regenerate=req=>new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));
 const save=req=>new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));
 route('get','/health',async(req,res)=>{await db.one('SELECT 1');res.json({ok:true,app:'BOT ARK',database:'postgres',discord:bot.status().ready})});
 route('get','/auth/discord-account',async(req,res)=>{if(!req.session.user)return res.redirect('/');try{const bridge=new URL(process.env.DISCORD_ACCOUNT_BRIDGE_URL||'https://dashboard-production-e07b.up.railway.app/api/mod-auth/login');bridge.searchParams.set('bridge',req.protocol+'://'+req.get('host'));res.redirect(bridge.toString())}catch{res.redirect('/')}});
 route('get','/auth/discord-bridge',async(req,res)=>{if(!req.session.user)return res.redirect('/');const data=verifyDiscordBridgeToken(req.query.token);if(req.session.user!=='owner'&&/^\d{15,22}$/.test(String(req.session.user))&&String(req.session.user)!==String(data.user.id))fail('forbidden',403);req.session.discordAccountUserId=String(data.user.id);req.session.discordAccountName=String(data.user.name||'Discord').slice(0,100);req.session.discordAccountGuilds=data.guilds;req.session.discordAccountLinkedAt=Date.now();await save(req);res.redirect('/')});
 route('get','/api/me',async(req,res)=>{const loggedIn=Boolean(req.session.user);let guilds=[];const linked=loggedIn&&Array.isArray(req.session.discordAccountGuilds)&&req.session.discordAccountGuilds.length?req.session.discordAccountGuilds:[];if(loggedIn){const installed=bot.installedGuilds(),live=new Map(installed.map(g=>[String(g.id),g]));if(linked.length&&(req.session.user==='owner'||!/^\d{15,22}$/.test(String(req.session.user))||String(req.session.user)===String(req.session.discordAccountUserId))){guilds=linked.map(g=>live.has(String(g.id))?{...g,...live.get(String(g.id)),installed:true,role:'admin'}:{...g,installed:false,memberCount:0,role:'admin'}).sort((a,b)=>a.name.localeCompare(b.name,'fr'))}else{guilds=req.session.role==='owner'?installed:await bot.accessibleGuilds(req.session.user);if(!guilds.length&&req.session.guildId){const row=await db.one('SELECT id,name FROM ark_guilds WHERE id=$1',[req.session.guildId]);if(row)guilds=[{...row,icon:null,installed:false,role:req.session.role}]}}}res.json({loggedIn,user:req.session.user||null,name:req.session.name||null,role:req.session.role||null,guildId:req.session.guildId||null,language:req.session.language||'fr',guilds,bot:bot.status(),discordLinked:Boolean(req.session.discordAccountLinkedAt),discordAccountUrl:'/auth/discord-account'})});
 route('post','/api/login',async(req,res)=>{limit(req);const {username,password}=req.body;const eq=(a,b)=>{const ah=s.sha(a||''),bh=s.sha(b||'');return crypto.timingSafeEqual(Buffer.from(ah),Buffer.from(bh))};if(typeof username!=='string'||typeof password!=='string'||!process.env.DASHBOARD_USER||!process.env.DASHBOARD_PASSWORD||!eq(username,process.env.DASHBOARD_USER)||!eq(password,process.env.DASHBOARD_PASSWORD))fail('invalidCredentials',401);await regenerate(req);Object.assign(req.session,{user:'owner',name:username,role:'owner'});await save(req);attemptMap.delete(req.ip);res.json({ok:true})});
 route('post','/api/discord-login',async(req,res)=>{limit(req);const token=v.text(100).parse(req.body.token);const row=await db.one('SELECT * FROM ark_login_links WHERE token_hash=$1 AND expires_at>$2',[s.sha(token),Date.now()]);if(!row)fail('expiredLink',401);await bot.verify(row.guild_id,row.user_id,row.role);const removed=await db.one('DELETE FROM ark_login_links WHERE token_hash=$1 RETURNING *',[row.token_hash]);if(!removed)fail('expiredLink',401);await regenerate(req);Object.assign(req.session,{user:row.user_id,name:row.name,role:row.role,guildId:row.guild_id,checkedAt:Date.now()});await save(req);res.json({ok:true})});
 route('post','/api/logout',async(req,res)=>{await new Promise(r=>req.session.destroy(r));res.json({ok:true})});
 route('post','/api/language',async(req,res)=>{req.session.language=v.z.enum(v.languages).parse(req.body.language);await save(req);res.json({ok:true})});
 route('post','/api/guilds',login,owner,async(req,res)=>{const id=v.id.parse(req.body.id),name=v.text(100).parse(req.body.name);await s.guild(id,name);req.session.guildId=id;await save(req);res.json({ok:true})});
 route('post','/api/guild/select',login,async(req,res)=>{const id=v.id.parse(req.body.id);let row=await db.one('SELECT id FROM ark_guilds WHERE id=$1',[id]);if(!row){const live=bot.installedGuilds().find(g=>String(g.id)===String(id));if(live){await s.guild(id,live.name);row=await db.one('SELECT id FROM ark_guilds WHERE id=$1',[id])}}if(!row)fail('notFound',404);if(req.session.role!=='owner'){const access=await bot.guildAccess(id,req.session.user);if(!access)fail('forbidden',403);req.session.role=access}req.session.guildId=id;req.session.checkedAt=Date.now();await save(req);res.json({ok:true,role:req.session.role})});
 route('get','/api/state',login,scope,async(req,res)=>{res.json(await s.snapshot(req.g,actor(req),req.session.role!=='player'))});
 route('get','/api/modules',login,scope,async(req,res)=>res.json(await modules.list(req.g)));
 route('get','/api/modules/:key',login,scope,async(req,res)=>res.json({module:await modules.get(req.g,req.params.key),records:await modules.records(req.g,req.params.key,100)}));
 route('post','/api/modules/:key',login,owner,scope,async(req,res)=>res.json(await modules.save(req.g,req.params.key,req.body||{})));
 route('get','/api/discord/channels',login,scope,async(req,res)=>res.json(await bot.guildChannels(req.g)));
 route('post','/api/seasons',login,staff,scope,async(req,res)=>res.json(await s.createSeason(req.g,actor(req),req.body)));
 route('post','/api/seasons/:id/publish',login,staff,scope,async(req,res)=>{await s.publishSeason(req.g,actor(req),req.params.id);res.json({ok:true})});
 route('post','/api/seasons/:id/archive',login,staff,scope,async(req,res)=>{await s.archiveSeason(req.g,actor(req),req.params.id);res.json({ok:true})});
 route('post','/api/quests',login,staff,scope,async(req,res)=>res.json(await s.createQuest(req.g,actor(req),req.body)));
 route('post','/api/quests/:id/toggle',login,staff,scope,async(req,res)=>{const row=await db.one('UPDATE ark_quests SET enabled=NOT enabled WHERE guild_id=$1 AND id=$2 RETURNING id',[req.g,req.params.id]);if(!row)fail('notFound',404);res.json({ok:true})});
 route('post','/api/quests/:id/claim',login,scope,async(req,res)=>res.json(await s.claimQuest(req.g,actor(req),req.params.id,String(req.body.proof||''))));
 route('post','/api/claims/:id/review',login,staff,scope,async(req,res)=>{res.json(await s.reviewClaim(req.g,actor(req),req.params.id,v.z.boolean().parse(req.body.approve)))});
 route('post','/api/rewards',login,staff,scope,async(req,res)=>res.json(await s.createReward(req.g,actor(req),req.body)));
 route('post','/api/rewards/:id/claim',login,scope,async(req,res)=>{const claim=await s.claimReward(req.g,actor(req),req.params.id);let automatic=false;try{automatic=await bot.deliverRole(claim)}catch(e){await s.audit(req.g,'BOT ARK','reward.delivery_pending',{id:claim.id})}res.json({ok:true,automatic})});
 route('post','/api/reward-claims/:id/deliver',login,staff,scope,async(req,res)=>res.json(await s.deliverReward(req.g,actor(req),req.params.id)));
 route('post','/api/members/:id',login,staff,scope,async(req,res)=>{await s.updateMember(req.g,actor(req),req.params.id,req.body);res.json({ok:true})});
 route('post','/api/profile',login,scope,async(req,res)=>{const game=v.text(100).parse(req.body.game_id),platform=v.z.enum(['PC','Xbox','PlayStation']).parse(req.body.platform);await s.member(req.g,actor(req),req.session.name);await db.query('UPDATE ark_members SET game_id=$3,platform=$4,verified=false WHERE guild_id=$1 AND user_id=$2',[req.g,actor(req),game,platform]);res.json({ok:true})});
 route('post','/api/tickets',login,scope,async(req,res)=>{let row=await s.openTicket(req.g,actor(req),String(req.body.title||''));try{if(actor(req)!=='owner')row=await bot.createTicketChannel(row)}catch(e){await s.audit(req.g,'BOT ARK','ticket.channel_pending',{id:row.id})}res.json(row)});
 route('get','/api/tickets/:id',login,scope,async(req,res)=>{const row=await s.ticket(req.g,actor(req),req.params.id,req.session.role!=='player');const messages=await db.all('SELECT * FROM ark_ticket_messages WHERE ticket_id=$1 ORDER BY id',[row.id]);res.json({...row,messages})});
 route('post','/api/tickets/:id/message',login,scope,async(req,res)=>{const message=await s.ticketMessage(req.g,actor(req),req.session.name,req.params.id,String(req.body.body||''),req.session.role!=='player');const ticket=await s.ticket(req.g,actor(req),req.params.id,true);try{await bot.mirrorMessage(ticket,req.session.name,message.body)}catch(e){await s.audit(req.g,'BOT ARK','ticket.mirror_pending',{id:ticket.id})}res.json(message)});
 route('post','/api/tickets/:id/close',login,scope,async(req,res)=>{const row=await s.closeTicket(req.g,actor(req),req.params.id,req.session.role!=='player');await bot.closeTicketChannel(row).catch(()=>{});res.json({ok:true})});
 route('get','/api/economy',login,scope,async(req,res)=>res.json(await s.economy(req.g,actor(req))));
 route('post','/api/rp/profile',login,scope,async(req,res)=>res.json(await s.saveRpProfile(req.g,actor(req),req.body||{})));
 route('post','/api/economy/transfer',login,scope,async(req,res)=>res.json(await s.transferCredits(req.g,actor(req),String(req.body.userId||''),req.body.amount)));
 route('post','/api/economy/credit',login,staff,scope,async(req,res)=>res.json(await s.grantCredits(req.g,actor(req),String(req.body.userId||''),req.body.amount)));
 route('post','/api/shop/items',login,staff,scope,async(req,res)=>res.json(await s.addShopItem(req.g,actor(req),req.body)));
 route('post','/api/shop/:id/buy',login,scope,async(req,res)=>res.json(await s.buyShopItem(req.g,actor(req),req.params.id)));
 route('post','/api/lottery/ticket',login,scope,async(req,res)=>res.json(await s.lotteryTicket(req.g,actor(req))));
 route('post','/api/lottery/draw',login,staff,scope,async(req,res)=>res.json(await s.drawLottery(req.g,actor(req))));
 route('get','/api/minigames/:game',login,scope,async(req,res)=>res.json(await s.playMiniGame(req.g,actor(req),req.params.game)));
 route('post','/api/minigames/:game',login,scope,async(req,res)=>res.json(await s.playMiniGame(req.g,actor(req),req.params.game,req.body.answer)));
 route('get','/api/settings',login,staff,scope,async(req,res)=>{const row=await db.one('SELECT config FROM ark_guilds WHERE id=$1',[req.g]);if(!row)fail('notFound',404);res.json(safeConfig(row.config))});
 route('post','/api/settings',login,staff,scope,async(req,res)=>{const input=v.settings.parse(req.body);const {nitrado_token,...config}=input;if(nitrado_token)config.nitrado_token_enc=vault.encrypt(nitrado_token);await db.query('UPDATE ark_guilds SET config=config||$2::jsonb WHERE id=$1',[req.g,JSON.stringify(config)]);await s.audit(req.g,actor(req),'settings.updated');res.json({ok:true})});
 route('post','/api/settings/webhook',login,staff,scope,async(req,res)=>{const token=crypto.randomBytes(32).toString('base64url');await db.query('UPDATE ark_guilds SET config=config||$2::jsonb WHERE id=$1',[req.g,JSON.stringify({webhook_secret_hash:s.sha(token)})]);await s.audit(req.g,actor(req),'webhook.rotated');res.json({secret:token,url:process.env.PUBLIC_BASE_URL+'/api/webhook/'+req.g})});
 route('post','/api/import/events',login,staff,scope,async(req,res)=>res.json(await s.ingest(req.g,actor(req),req.body.events)));
 route('post','/api/import/logs',login,staff,scope,async(req,res)=>res.json(await s.rawLogs(req.g,'import',req.body.text)));
 route('post','/api/webhook/:guild',async(req,res)=>{const id=v.id.parse(req.params.guild);const row=await db.one('SELECT config FROM ark_guilds WHERE id=$1',[id]);const supplied=s.sha(String(req.headers.authorization||'').replace(/^Bearer /,''));const expected=row?.config.webhook_secret_hash;if(!expected||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))fail('unauthorized',401);res.json(await s.ingest(id,'webhook',req.body.events))});
 route('get','/api/nitrado/services',login,staff,scope,async(req,res)=>res.json(await nitrado.services(req.g)));
 route('post','/api/nitrado/poll',login,staff,scope,async(req,res)=>res.json(await nitrado.poll(req.g)));
 route('get','/api/top-servers',async(req,res)=>res.json(await s.topServers()));
 route('post','/api/top-servers',async(req,res)=>{const supplied=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const ownerSession=req.session?.role==='owner';if(!ownerSession&&(!process.env.TOP_SERVERS_WRITE_KEY||supplied!==process.env.TOP_SERVERS_WRITE_KEY))fail('forbidden',403);res.json(await s.saveTopServer(ownerSession?actor(req):'network',req.body||{}));});
 route('post','/api/top-servers/:id/vote',async(req,res)=>res.json(await s.voteTopServer(req.params.id,req.ip,req.get('user-agent')||'')));
 route('post','/api/file-validator',login,staff,async(req,res)=>res.json(fileValidator.validateFile(String(req.body.filename||''),String(req.body.content||''))));
 route('get','/api/premium/plans',async(req,res)=>res.json({paypalUrl:premium.PAYPAL_URL,plans:premium.PLANS}));
 route('get','/api/premium',login,scope,async(req,res)=>res.json(await premium.status(req.g,actor(req))));
 route('post','/api/premium/payment-request',login,scope,async(req,res)=>res.json(await premium.requestPayment(req.g,actor(req),String(req.body.product||''),String(req.body.billing||''))));
 route('post','/api/premium/redeem',login,scope,async(req,res)=>res.json(await premium.redeem(req.g,actor(req),String(req.body.code||''))));
 route('post','/api/premium/servers',login,scope,async(req,res)=>res.json(await premium.registerServer(req.g,actor(req),req.body.label,req.body.serviceId)));
 route('delete','/api/premium/servers/:id',login,scope,async(req,res)=>res.json(await premium.removeServer(req.g,req.params.id)));
 route('get','/api/premium/admin',login,owner,scope,async(req,res)=>res.json(await premium.admin(req.g)));
 route('post','/api/premium/admin/code',login,owner,async(req,res)=>res.json(await premium.generateCode(actor(req),String(req.body.product||''),String(req.body.billing||''))));
 route('post','/api/premium/admin/approve/:id',login,owner,async(req,res)=>res.json(await premium.approvePayment(actor(req),req.params.id)));
 route('post','/api/setup/discord',login,owner,async(req,res)=>{const clientId=v.id.parse(req.body.clientId),token=v.text(300).parse(req.body.token);res.json(await bot.start({clientId,token}))});
 app.use(express.static(path.join(__dirname,'..','public'),{maxAge:'5m',etag:true}));
 app.use((err,req,res,next)=>{console.error('BOT ARK API :',err.code||err.name);if(res.headersSent)return next(err);const isValidation=err.name==='ZodError';const code=isValidation?(err.issues?.find(i=>i.code==='custom')?.message||'invalidInput'):err.status?err.code:'error';res.status(isValidation?400:err.status||500).json({error:code})});
 return app;
}
module.exports=app;
