const db=require('./db');
const crypto=require('node:crypto');
const {AppError,fail}=require('./errors');
const v=require('./validation');
const sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const NOW=()=>new Date();
function periodKey(q,now=NOW()){
 const d=new Date(now);if(q.period==='season')return 'season:'+q.season_id;
 if(q.period==='daily')return d.toISOString().slice(0,10);
 d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return 'week:'+d.toISOString().slice(0,10);
}
async function audit(guild,actor,action,details={}){await db.query('INSERT INTO ark_audit(guild_id,actor,action,details) VALUES($1,$2,$3,$4)',[guild,actor,action,details])}
async function guild(id,name){v.id.parse(id);return db.one('INSERT INTO ark_guilds(id,name) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name RETURNING *',[id,name.slice(0,100)])}
async function member(g,user,name){return db.one('INSERT INTO ark_members(guild_id,user_id,name) VALUES($1,$2,$3) ON CONFLICT(guild_id,user_id) DO UPDATE SET name=EXCLUDED.name RETURNING *',[g,user,String(name).slice(0,100)])}
async function active(g,now=NOW()){return db.one("SELECT * FROM ark_seasons WHERE guild_id=$1 AND status='published' AND starts_at<=$2 AND ends_at>$2 ORDER BY starts_at DESC LIMIT 1",[g,now])}
async function seasonInGuild(g,id){const s=await db.one('SELECT * FROM ark_seasons WHERE guild_id=$1 AND id=$2',[g,id]);if(!s)fail('notFound',404);return s}
async function createSeason(g,actor,input){const s=v.season.parse(input);return db.tx(async()=>{
 await db.query('SELECT id FROM ark_guilds WHERE id=$1 FOR UPDATE',[g]);
 if(s.status==='published'&&await db.one("SELECT id FROM ark_seasons WHERE guild_id=$1 AND status='published' AND starts_at<$3 AND ends_at>$2",[g,s.starts_at,s.ends_at]))fail('seasonOverlap');
 const row=await db.one('INSERT INTO ark_seasons(guild_id,name,starts_at,ends_at,xp_per_tier,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[g,s.name,s.starts_at,s.ends_at,s.xp_per_tier,s.status]);await audit(g,actor,'season.created',{id:row.id});return row;
})}
async function publishSeason(g,actor,id){return db.tx(async()=>{await db.query('SELECT id FROM ark_guilds WHERE id=$1 FOR UPDATE',[g]);const s=await seasonInGuild(g,id);if(s.status==='archived')fail('seasonEnded');if(await db.one("SELECT id FROM ark_seasons WHERE guild_id=$1 AND id<>$2 AND status='published' AND starts_at<$4 AND ends_at>$3",[g,id,s.starts_at,s.ends_at]))fail('seasonOverlap');await db.query("UPDATE ark_seasons SET status='published' WHERE guild_id=$1 AND id=$2",[g,id]);await audit(g,actor,'season.published',{id});})}
async function archiveSeason(g,actor,id){await seasonInGuild(g,id);await db.query("UPDATE ark_seasons SET status='archived' WHERE guild_id=$1 AND id=$2",[g,id]);await audit(g,actor,'season.archived',{id})}
async function createQuest(g,actor,input){const q=v.quest.parse(input);const s=await seasonInGuild(g,q.season_id);if(s.status==='archived')fail('seasonEnded');const row=await db.one('INSERT INTO ark_quests(guild_id,season_id,title,description,kind,target,goal,xp,period) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[g,q.season_id,q.title,q.description,q.kind,q.target,q.goal,q.xp,q.period]);await audit(g,actor,'quest.created',{id:row.id});return row}
async function createReward(g,actor,input){const r=v.reward.parse(input);await seasonInGuild(g,r.season_id);const row=await db.one('INSERT INTO ark_rewards(guild_id,season_id,tier,title,description,premium,kind,role_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[g,r.season_id,r.tier,r.title,r.description,r.premium,r.kind,r.role_id||null]);await audit(g,actor,'reward.created',{id:row.id});return row}
async function quests(g,user){const s=await active(g);if(!s)return[];const rows=await db.all('SELECT * FROM ark_quests WHERE guild_id=$1 AND season_id=$2 AND enabled ORDER BY id',[g,s.id]);const progress=await db.all('SELECT * FROM ark_quest_progress WHERE guild_id=$1 AND user_id=$2',[g,user]);return rows.map(q=>({...q,progress:progress.find(p=>p.quest_id===q.id&&p.period_key===periodKey(q))?.value||0,completed:Boolean(progress.find(p=>p.quest_id===q.id&&p.period_key===periodKey(q))?.completed_at)}))}
async function applicableQuest(g,id,now=NOW()){const s=await active(g,now);if(!s)fail('noSeason');const q=await db.one('SELECT * FROM ark_quests WHERE guild_id=$1 AND id=$2 AND season_id=$3 AND enabled',[g,id,s.id]);if(!q)fail('notFound',404);return q}
async function addProgress(g,user,q,amount,key){
 await db.query('INSERT INTO ark_quest_progress(guild_id,quest_id,user_id,period_key) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[g,q.id,user,key]);
 const p=await db.one('SELECT * FROM ark_quest_progress WHERE guild_id=$1 AND quest_id=$2 AND user_id=$3 AND period_key=$4 FOR UPDATE',[g,q.id,user,key]);
 if(p.completed_at)return {completed:false,already:true};const value=Math.min(q.goal,p.value+amount);const complete=value>=q.goal;
 await db.query('UPDATE ark_quest_progress SET value=$5,completed_at=$6 WHERE guild_id=$1 AND quest_id=$2 AND user_id=$3 AND period_key=$4',[g,q.id,user,key,value,complete?NOW():null]);
 if(complete){await db.query('INSERT INTO ark_progress(guild_id,season_id,user_id,xp) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,season_id,user_id) DO UPDATE SET xp=ark_progress.xp+EXCLUDED.xp',[g,q.season_id,user,q.xp]);await audit(g,user,'quest.completed',{quest_id:q.id,xp:q.xp});}return {completed:complete,value,xp:complete?q.xp:0};
}
async function claimQuest(g,user,id,proof){v.text(2000).parse(proof);const q=await applicableQuest(g,id);const key=periodKey(q);const completed=await db.one('SELECT completed_at FROM ark_quest_progress WHERE guild_id=$1 AND quest_id=$2 AND user_id=$3 AND period_key=$4',[g,id,user,key]);if(completed?.completed_at)fail('alreadyCompleted');try{return await db.one('INSERT INTO ark_claims(guild_id,user_id,quest_id,period_key,proof) VALUES($1,$2,$3,$4,$5) RETURNING *',[g,user,id,key,proof])}catch(e){if(e.code==='23505')fail('alreadyPending');throw e}}
async function reviewClaim(g,actor,id,approve){return db.tx(async()=>{
 const c=await db.one('SELECT * FROM ark_claims WHERE guild_id=$1 AND id=$2 FOR UPDATE',[g,id]);if(!c)fail('notFound',404);if(c.status!=='pending')fail('alreadyReviewed');
 let result={};if(approve){const q=await applicableQuest(g,c.quest_id);if(periodKey(q)!==c.period_key)fail('claimExpired');result=await addProgress(g,c.user_id,q,q.goal,c.period_key)}
 await db.query('UPDATE ark_claims SET status=$3,reviewer=$4,reviewed_at=NOW() WHERE guild_id=$1 AND id=$2',[g,id,approve?'approved':'rejected',actor]);await audit(g,actor,'claim.reviewed',{id,approve});return result;
})}
async function pass(g,user){const s=await active(g);if(!s)return {season:null,xp:0,tier:0,rewards:[]};const p=await db.one('SELECT xp,premium FROM ark_progress WHERE guild_id=$1 AND season_id=$2 AND user_id=$3',[g,s.id,user]);const xp=p?.xp||0;const tier=Math.floor(xp/s.xp_per_tier);const ownerPremium=String(user)==='owner';const hasPremium=ownerPremium||Boolean(p?.premium);const rewards=await db.all('SELECT r.*,c.status AS claim_status FROM ark_rewards r LEFT JOIN ark_reward_claims c ON c.reward_id=r.id AND c.guild_id=r.guild_id AND c.user_id=$3 WHERE r.guild_id=$1 AND r.season_id=$2 ORDER BY tier,premium',[g,s.id,user]);return {season:s,xp,tier,premium:hasPremium,rewards:rewards.map(r=>({...r,unlocked:tier>=r.tier&&(!r.premium||hasPremium)}))}}
async function claimReward(g,user,id){return db.tx(async()=>{const state=await pass(g,user);const reward=state.rewards.find(r=>r.id===Number(id));if(!reward)fail('notFound',404);if(!reward.unlocked)fail('rewardLocked');try{const claim=await db.one('INSERT INTO ark_reward_claims(guild_id,user_id,reward_id) VALUES($1,$2,$3) RETURNING *',[g,user,id]);await audit(g,user,'reward.claimed',{id});return {...claim,reward}}catch(e){if(e.code==='23505')fail('alreadyClaimed');throw e}})}
async function deliverReward(g,actor,id){const claim=await db.one("UPDATE ark_reward_claims SET status='delivered',delivered_at=NOW() WHERE guild_id=$1 AND id=$2 AND status='pending' RETURNING *",[g,id]);if(!claim)fail('notFound',404);await audit(g,actor,'reward.delivered',{id});return claim}
async function openTicket(g,user,title){v.text(150).parse(title);const existing=await db.one("SELECT * FROM ark_tickets WHERE guild_id=$1 AND user_id=$2 AND status='open'",[g,user]);if(existing)return existing;try{const t=await db.one('INSERT INTO ark_tickets(guild_id,user_id,title) VALUES($1,$2,$3) RETURNING *',[g,user,title]);await audit(g,user,'ticket.opened',{id:t.id});return t}catch(e){if(e.code==='23505')return db.one("SELECT * FROM ark_tickets WHERE guild_id=$1 AND user_id=$2 AND status='open'",[g,user]);throw e}}
async function ticket(g,user,id,staff){const t=await db.one('SELECT * FROM ark_tickets WHERE guild_id=$1 AND id=$2',[g,id]);if(!t||(!staff&&t.user_id!==user))fail('notFound',404);return t}
async function ticketMessage(g,user,name,id,body,staff,discordId){v.text(2000).parse(body);const t=await ticket(g,user,id,staff);if(t.status!=='open')fail('ticketClosed');return db.one('INSERT INTO ark_ticket_messages(ticket_id,author_id,author_name,body,discord_message_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(discord_message_id) DO NOTHING RETURNING *',[id,user,name.slice(0,100),body,discordId||null])}
async function closeTicket(g,user,id,staff){const t=await ticket(g,user,id,staff);await db.query("UPDATE ark_tickets SET status='closed',closed_at=NOW() WHERE guild_id=$1 AND id=$2",[g,id]);await audit(g,user,'ticket.closed',{id});return t}
async function updateMember(g,actor,user,body){v.id.parse(user);const m=await db.one('SELECT * FROM ark_members WHERE guild_id=$1 AND user_id=$2',[g,user]);if(!m)fail('notFound',404);const gameId=body.game_id? v.text(100).parse(body.game_id):null;const platform=v.z.enum(['PC','Xbox','PlayStation']).parse(body.platform);const verified=Boolean(body.verified&&gameId);try{const current=await active(g);if(body.premium&&!current)fail('noSeason');await db.query('UPDATE ark_members SET game_id=$3,platform=$4,verified=$5 WHERE guild_id=$1 AND user_id=$2',[g,user,gameId,platform,verified]);if(current)await db.query('INSERT INTO ark_progress(guild_id,season_id,user_id,premium) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,season_id,user_id) DO UPDATE SET premium=EXCLUDED.premium',[g,current.id,user,Boolean(body.premium)]);await audit(g,actor,'member.updated',{user,verified,premium:Boolean(body.premium)})}catch(e){if(e.code==='23505')fail('identityUsed');throw e}}
async function ingest(g,actor,input){const events=v.z.array(v.event).min(1).max(250).parse(input);return db.tx(async()=>{
 let accepted=0,duplicates=0,unlinked=0,completed=0;
 for(const e of events){const when=new Date(e.occurredAt);if(when.getTime()>Date.now()+60000)fail('futureEvent');
 const inserted=await db.one('INSERT INTO ark_events(guild_id,event_key,player_id,kind,target,amount,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING RETURNING id',[g,e.eventId,e.playerId,e.type,e.target,e.amount,when]);if(!inserted){duplicates++;continue}accepted++;
 const m=await db.one('SELECT * FROM ark_members WHERE guild_id=$1 AND game_id=$2 AND verified',[g,e.playerId]);if(!m){unlinked++;continue}
 const s=await active(g,when);const current=await active(g);if(!s||s.id!==current?.id)continue;
 const list=await db.all('SELECT * FROM ark_quests WHERE guild_id=$1 AND season_id=$2 AND kind=$3 AND enabled',[g,s.id,e.type]);
 for(const q of list){if(q.target&&q.target.toLowerCase()!==e.target.toLowerCase())continue;if(periodKey(q,when)!==periodKey(q))continue;const result=await addProgress(g,m.user_id,q,e.amount,periodKey(q,when));if(result.completed)completed++;}
 }await audit(g,actor,'events.imported',{accepted,duplicates,unlinked,completed});return {accepted,duplicates,unlinked,completed};
})}

function arkCoords(line){const patterns=[/\b(?:pos|position|location|loc)\s*[:=]?\s*<?\s*X?\s*=?\s*(-?\d+(?:\.\d+)?)\s*[, ]+Y?\s*=?\s*(-?\d+(?:\.\d+)?)\s*[, ]+Z?\s*=?\s*(-?\d+(?:\.\d+)?)/i,/\bX\s*=\s*(-?\d+(?:\.\d+)?)\s*[, ]+Y\s*=\s*(-?\d+(?:\.\d+)?)\s*[, ]+Z\s*=\s*(-?\d+(?:\.\d+)?)/i];for(const p of patterns){const m=line.match(p);if(m)return{x:Number(m[1]),y:Number(m[2]),z:Number(m[3])};}return{x:null,y:null,z:null}}
function arkWhen(line){const m=line.match(/(20\d\d)[.\/-](\d\d)[.\/-](\d\d)[ T-](\d\d)[.:](\d\d)[.:](\d\d)/);if(m){const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]));if(Number.isFinite(d.getTime()))return d;}return new Date()}
function parseArkActivity(line){
 const s=String(line||'').trim();if(!s)return null;const pos=arkCoords(s),occurredAt=arkWhen(s);let m;
 if((m=s.match(/Join succeeded:\s*(.+?)(?:\s*\(|$)/i))||(m=s.match(/Player\s+["']?([^"']+?)["']?\s+(?:has\s+)?(?:joined|connected)\b/i)))return{event_type:'connect',player_name:m[1].trim(),...pos,occurredAt};
 if((m=s.match(/Logout:\s*(.+?)(?:\s*\(|$)/i))||(m=s.match(/Player\s+["']?([^"']+?)["']?\s+(?:has\s+)?(?:left|disconnected|logged out)\b/i)))return{event_type:'disconnect',player_name:m[1].trim(),...pos,occurredAt};
 if((m=s.match(/(.+?)\s+was killed by\s+(.+?)(?:\s+with\s+(.+?))?(?:\s+at\s+|$)/i)))return{event_type:'death',player_name:m[1].trim().replace(/^Player\s+["']?|["']$/g,''),actor_name:m[2].trim().replace(/^Player\s+["']?|["']$/g,''),weapon:(m[3]||'').trim(),cause:'killed',...pos,occurredAt};
 if((m=s.match(/Player\s+["']?([^"']+?)["']?.*?\b(?:died|was killed)\b(?:\s+(?:by|from)\s+([^,;]+))?/i)))return{event_type:'death',player_name:m[1].trim(),cause:(m[2]||'death').trim(),...pos,occurredAt};
 if((m=s.match(/Player\s+["']?([^"']+?)["']?.*?\b(?:placed|built|constructed|deployed)\b\s+(?:an?\s+|the\s+)?["']?([^"',;]+)["']?/i))||(m=s.match(/^(.+?)\s+\b(?:placed|built|constructed|deployed)\b\s+(.+?)(?:\s+at\s+|$)/i)))return{event_type:'build',player_name:m[1].trim(),object_name:m[2].trim(),...pos,occurredAt};
 return null;
}

async function rawLogs(g,source,text){if(typeof text!=='string'||text.length>1000000)fail('logTooLarge');const lines=text.split(/\r?\n/).filter(Boolean).slice(-1000);const occurrences=new Map();let added=0,activityAdded=0;for(const line of lines){const n=occurrences.get(line)||0;occurrences.set(line,n+1);const key=sha(line+':'+n);const row=await db.one('INSERT INTO ark_game_logs(guild_id,source,event_key,line) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING id',[g,source.slice(0,100),key,line.slice(0,8000)]);if(!row)continue;added++;const e=parseArkActivity(line);if(e){const a=await db.one('INSERT INTO ark_activity_logs(guild_id,event_key,event_type,player_name,player_id,actor_name,cause,weapon,object_name,x,y,z,occurred_at,source,raw_line) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT DO NOTHING RETURNING id',[g,key,e.event_type,e.player_name||'',e.player_id||'',e.actor_name||'',e.cause||'',e.weapon||'',e.object_name||'',e.x,e.y,e.z,e.occurredAt,source.slice(0,100),line.slice(0,8000)]);if(a)activityAdded++;}}return {added,activityAdded}}
async function snapshot(g,user,staff){const [season,questRows,passState,leaderboard,tickets,stats]=await Promise.all([
 active(g),quests(g,user),pass(g,user),db.all('SELECT p.user_id,m.name,p.xp FROM ark_progress p JOIN ark_members m ON m.guild_id=p.guild_id AND m.user_id=p.user_id JOIN ark_seasons s ON s.id=p.season_id WHERE p.guild_id=$1 AND s.status=\'published\' AND s.starts_at<=NOW() AND s.ends_at>NOW() ORDER BY p.xp DESC,m.name LIMIT 30',[g]),db.all('SELECT * FROM ark_tickets WHERE guild_id=$1'+(staff?'':' AND user_id=$2')+' ORDER BY id DESC LIMIT 100',staff?[g]:[g,user]),db.one('SELECT (SELECT COUNT(*)::int FROM ark_members WHERE guild_id=$1) AS members,(SELECT COUNT(*)::int FROM ark_tickets WHERE guild_id=$1 AND status=\'open\') AS tickets,(SELECT COUNT(*)::int FROM ark_claims WHERE guild_id=$1 AND status=\'pending\') AS pending',[g])]);
 const result={season,quests:questRows,pass:passState,leaderboard,tickets,stats};
 if(staff){const [seasons,allQuests,rewards,claims,members,auditRows,logs,rewardClaims,activity]=await Promise.all([
 db.all('SELECT * FROM ark_seasons WHERE guild_id=$1 ORDER BY starts_at DESC',[g]),db.all('SELECT * FROM ark_quests WHERE guild_id=$1 ORDER BY id',[g]),db.all('SELECT * FROM ark_rewards WHERE guild_id=$1 ORDER BY tier,id',[g]),db.all('SELECT c.*,q.title,m.name FROM ark_claims c JOIN ark_quests q ON q.id=c.quest_id LEFT JOIN ark_members m ON m.guild_id=c.guild_id AND m.user_id=c.user_id WHERE c.guild_id=$1 ORDER BY c.id DESC LIMIT 100',[g]),db.all("SELECT m.*,COALESCE(p.premium,false) AS premium FROM ark_members m LEFT JOIN ark_seasons s ON s.guild_id=m.guild_id AND s.status='published' AND s.starts_at<=NOW() AND s.ends_at>NOW() LEFT JOIN ark_progress p ON p.guild_id=m.guild_id AND p.user_id=m.user_id AND p.season_id=s.id WHERE m.guild_id=$1 ORDER BY m.name",[g]),db.all('SELECT * FROM ark_audit WHERE guild_id=$1 ORDER BY id DESC LIMIT 100',[g]),db.all('SELECT * FROM ark_game_logs WHERE guild_id=$1 ORDER BY id DESC LIMIT 100',[g]),db.all('SELECT c.*,r.title,m.name FROM ark_reward_claims c JOIN ark_rewards r ON r.id=c.reward_id LEFT JOIN ark_members m ON m.guild_id=c.guild_id AND m.user_id=c.user_id WHERE c.guild_id=$1 ORDER BY c.id DESC LIMIT 100',[g]),db.all('SELECT * FROM ark_activity_logs WHERE guild_id=$1 ORDER BY occurred_at DESC,id DESC LIMIT 200',[g])]);
 Object.assign(result,{seasons,allQuests,rewards,claims,members,audit:auditRows,logs,rewardClaims,activity});}
 return result;
}
async function economy(g,user){await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,user]);const wallet=await db.one('SELECT balance FROM ark_wallets WHERE guild_id=$1 AND user_id=$2',[g,user]);const shop=await db.all('SELECT id,name,description,price,delivery FROM ark_shop_items WHERE guild_id=$1 AND enabled ORDER BY price,name',[g]);const orders=await db.all('SELECT o.*,i.name FROM ark_shop_orders o JOIN ark_shop_items i ON i.id=o.item_id WHERE o.guild_id=$1 AND o.user_id=$2 ORDER BY o.id DESC LIMIT 20',[g,user]);const drawKey=new Date().toISOString().slice(0,10);const tickets=await db.all('SELECT id,cost,created_at FROM ark_lottery_tickets WHERE guild_id=$1 AND user_id=$2 AND draw_key=$3 ORDER BY id DESC',[g,user,drawKey]);const pot=await db.one('SELECT COALESCE(SUM(cost),0)::bigint AS pot,COUNT(*)::int AS tickets FROM ark_lottery_tickets WHERE guild_id=$1 AND draw_key=$2',[g,drawKey]);const games=await db.all('SELECT game,MAX(score)::int AS best,COALESCE(SUM(reward),0)::bigint AS rewards FROM ark_minigame_scores WHERE guild_id=$1 AND user_id=$2 GROUP BY game',[g,user]);const transactions=await db.all('SELECT * FROM ark_wallet_transactions WHERE guild_id=$1 AND user_id=$2 ORDER BY id DESC LIMIT 30',[g,user]);const profile=await db.one('SELECT * FROM ark_rp_profiles WHERE guild_id=$1 AND user_id=$2',[g,user]);return {balance:Number(wallet.balance),shop,orders,transactions,profile:profile||{job:'Survivant',faction:'',bio:''},lottery:{drawKey,pot:Number(pot.pot),tickets:Number(pot.tickets),mine:tickets.length},games}}
async function saveRpProfile(g,user,input){const job=String(input.job||'Survivant').trim().slice(0,60)||'Survivant',faction=String(input.faction||'').trim().slice(0,60),bio=String(input.bio||'').trim().slice(0,300);return db.one("INSERT INTO ark_rp_profiles(guild_id,user_id,job,faction,bio) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guild_id,user_id) DO UPDATE SET job=EXCLUDED.job,faction=EXCLUDED.faction,bio=EXCLUDED.bio,updated_at=NOW() RETURNING *",[g,user,job,faction,bio])}
async function transferCredits(g,from,to,amount){amount=Math.floor(Number(amount));if(!Number.isSafeInteger(amount)||amount<=0||from===to)fail('invalidInput',400);return db.tx(async()=>{await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2),($1,$3) ON CONFLICT DO NOTHING',[g,from,to]);const w=await db.one('SELECT * FROM ark_wallets WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[g,from]);if(Number(w.balance)<amount)fail('insufficientCredits',400);await db.query('UPDATE ark_wallets SET balance=balance-$3 WHERE guild_id=$1 AND user_id=$2',[g,from,amount]);await db.query('UPDATE ark_wallets SET balance=balance+$3 WHERE guild_id=$1 AND user_id=$2',[g,to,amount]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5),($1,$6,$7,$8,$9)',[g,from,-amount,'transfer',{to},to,amount,'transfer_received',{from}]);return{amount,balance:Number(w.balance)-amount}})}
async function grantCredits(g,actor,user,amount){amount=Math.floor(Number(amount));if(!Number.isSafeInteger(amount)||amount<=0)fail('invalidInput',400);await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,user]);const row=await db.one('UPDATE ark_wallets SET balance=balance+$3 WHERE guild_id=$1 AND user_id=$2 RETURNING balance',[g,user,amount]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5)',[g,user,amount,'admin_credit',{actor}]);return{balance:Number(row.balance)}}
async function addShopItem(g,actor,input){const name=String(input.name||'').trim().slice(0,100),description=String(input.description||'').trim().slice(0,500),price=Math.floor(Number(input.price));if(!name||!Number.isSafeInteger(price)||price<0)fail('invalidInput',400);const row=await db.one('INSERT INTO ark_shop_items(guild_id,name,description,price,delivery) VALUES($1,$2,$3,$4,$5) RETURNING *',[g,name,description,price,input.delivery&&typeof input.delivery==='object'?input.delivery:{}]);await audit(g,actor,'shop.item_created',{id:row.id});return row}
async function buyShopItem(g,user,id){return db.tx(async()=>{await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,user]);const item=await db.one('SELECT * FROM ark_shop_items WHERE guild_id=$1 AND id=$2 AND enabled FOR UPDATE',[g,id]);if(!item)fail('notFound',404);const wallet=await db.one('SELECT * FROM ark_wallets WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[g,user]);if(Number(wallet.balance)<Number(item.price))fail('insufficientCredits',400);await db.query('UPDATE ark_wallets SET balance=balance-$3 WHERE guild_id=$1 AND user_id=$2',[g,user,item.price]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5)',[g,user,-Number(item.price),'shop',{item_id:item.id,name:item.name}]);const order=await db.one('INSERT INTO ark_shop_orders(guild_id,user_id,item_id,price) VALUES($1,$2,$3,$4) RETURNING *',[g,user,item.id,item.price]);await audit(g,user,'shop.purchase',{order:order.id,item:item.id});return order})}
async function lotteryTicket(g,user){const cost=100,drawKey=new Date().toISOString().slice(0,10);return db.tx(async()=>{await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,user]);const w=await db.one('SELECT * FROM ark_wallets WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[g,user]);if(Number(w.balance)<cost)fail('insufficientCredits',400);await db.query('UPDATE ark_wallets SET balance=balance-$3 WHERE guild_id=$1 AND user_id=$2',[g,user,cost]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5)',[g,user,-cost,'lottery',{drawKey}]);const row=await db.one('INSERT INTO ark_lottery_tickets(guild_id,user_id,draw_key,cost) VALUES($1,$2,$3,$4) RETURNING *',[g,user,drawKey,cost]);await audit(g,user,'lottery.ticket',{id:row.id,drawKey});return row})}
async function drawLottery(g,actor){const drawKey=new Date().toISOString().slice(0,10);return db.tx(async()=>{if(await db.one('SELECT id FROM ark_lottery_draws WHERE guild_id=$1 AND draw_key=$2',[g,drawKey]))fail('alreadyDrawn',400);const tickets=await db.all('SELECT * FROM ark_lottery_tickets WHERE guild_id=$1 AND draw_key=$2 ORDER BY id FOR UPDATE',[g,drawKey]);if(!tickets.length)fail('notFound',404);const winner=tickets[crypto.randomInt(tickets.length)],prize=tickets.reduce((a,x)=>a+Number(x.cost),0);await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,winner.user_id]);await db.query('UPDATE ark_wallets SET balance=balance+$3 WHERE guild_id=$1 AND user_id=$2',[g,winner.user_id,prize]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5)',[g,winner.user_id,prize,'lottery_win',{drawKey}]);const draw=await db.one('INSERT INTO ark_lottery_draws(guild_id,draw_key,winner_user_id,prize,drawn_at) VALUES($1,$2,$3,$4,NOW()) RETURNING *',[g,drawKey,winner.user_id,prize]);await audit(g,actor,'lottery.draw',{winner:winner.user_id,prize});return draw})}

function topText(value,max=120){const s=String(value??'').trim();if(!s||s.length>max||/[\r\n\0]/.test(s))fail('invalidInput',400);return s}
function topOptional(value,max=500){const s=String(value??'').trim();if(s.length>max||/[\r\n\0]/.test(s))fail('invalidInput',400);return s}
function topUrl(value){const s=topOptional(value,500);if(s&&!/^https?:\/\//i.test(s))fail('invalidInput',400);return s}
function officialSource(value){return ['DAYZ GATE','BOT ARK','EXTINCTION ++ RSS','CMD TOP SERVEUR','CMD Top Serveur'].includes(String(value||''))}
async function topServers(filters={}){
 const args=[],where=['s.enabled=TRUE'];
 if(filters.game){args.push(String(filters.game).trim().toLowerCase());where.push('LOWER(s.game)=$'+args.length)}
 if(filters.q){args.push('%'+String(filters.q).trim().toLowerCase().slice(0,100)+'%');where.push("(LOWER(s.name) LIKE $"+args.length+" OR LOWER(s.description) LIKE $"+args.length+" OR LOWER(s.game) LIKE $"+args.length+")")}
 const sort=String(filters.sort||'monthly');
 const order=sort==='votes'?'votes DESC,votes_month DESC':sort==='new'?'s.created_at DESC':sort==='clicks'?'clicks_month DESC,votes_month DESC':'votes_month DESC,votes_24h DESC,votes DESC';
 const limit=Math.max(1,Math.min(100,Number(filters.limit)||100));args.push(limit);
 return db.all(`SELECT s.id,s.guild_id,s.name,s.game,s.map,s.platform,s.address,s.website,s.discord_url,s.description,s.image_url,s.source_bot,s.verified,s.created_at,s.updated_at,
  COUNT(DISTINCT v.id)::int AS votes,
  COUNT(DISTINCT v.id) FILTER (WHERE v.created_at>=date_trunc('month',NOW()))::int AS votes_month,
  COUNT(DISTINCT v.id) FILTER (WHERE v.created_at>=NOW()-INTERVAL '24 hours')::int AS votes_24h,
  COUNT(DISTINCT vi.id)::int AS clicks,
  COUNT(DISTINCT vi.id) FILTER (WHERE vi.created_at>=date_trunc('month',NOW()))::int AS clicks_month,
  COUNT(DISTINCT vi.id) FILTER (WHERE vi.created_at>=NOW()-INTERVAL '24 hours')::int AS clicks_24h
  FROM shared_top_servers s
  LEFT JOIN shared_top_server_votes v ON v.server_id=s.id
  LEFT JOIN shared_top_server_visits vi ON vi.server_id=s.id
  WHERE ${where.join(' AND ')}
  GROUP BY s.id ORDER BY ${order},s.name ASC LIMIT $${args.length}`,args)
}
async function topServerById(id){
 const rows=await topServers({limit:100});return rows.find(x=>String(x.id)===String(id))||null;
}
async function saveTopServer(actor,input){
 const id=topOptional(input.id,80)||crypto.randomUUID(),name=topText(input.name,100),game=topText(input.game,60),map=topOptional(input.map,100),platform=topOptional(input.platform,80),address=topOptional(input.address,200),website=topUrl(input.website),discord=topUrl(input.discord_url),description=topOptional(input.description,700),image=topUrl(input.image_url),source=topOptional(input.source_bot||'CMD Top Serveur',60)||'CMD Top Serveur',guildId=topOptional(input.guild_id,40),ownerUserId=topOptional(input.owner_user_id,40),verified=Boolean(input.verified)||officialSource(source);
 const row=await db.one(`INSERT INTO shared_top_servers(id,guild_id,owner_user_id,name,game,map,platform,address,website,discord_url,description,image_url,source_bot,verified)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
 ON CONFLICT(id) DO UPDATE SET guild_id=EXCLUDED.guild_id,owner_user_id=EXCLUDED.owner_user_id,name=EXCLUDED.name,game=EXCLUDED.game,map=EXCLUDED.map,platform=EXCLUDED.platform,address=EXCLUDED.address,website=EXCLUDED.website,discord_url=EXCLUDED.discord_url,description=EXCLUDED.description,image_url=EXCLUDED.image_url,source_bot=EXCLUDED.source_bot,verified=EXCLUDED.verified,enabled=TRUE,updated_at=NOW()
 RETURNING *`,[id,guildId,ownerUserId,name,game,map,platform,address,website,discord,description,image,source,verified]);
 return row;
}
async function ownerTopServers(ownerUserId){return db.all('SELECT * FROM shared_top_servers WHERE owner_user_id=$1 ORDER BY updated_at DESC',[topText(ownerUserId,40)])}
async function updateTopServer(ownerUserId,id,input){
 const current=await db.one('SELECT * FROM shared_top_servers WHERE id=$1 AND owner_user_id=$2',[String(id),String(ownerUserId)]);if(!current)fail('notFound',404);
 return saveTopServer(ownerUserId,{...current,...input,id:current.id,owner_user_id:current.owner_user_id,guild_id:input.guild_id??current.guild_id,source_bot:current.source_bot,verified:current.verified});
}
async function deleteTopServer(ownerUserId,id){
 const row=await db.one('UPDATE shared_top_servers SET enabled=FALSE,updated_at=NOW() WHERE id=$1 AND owner_user_id=$2 RETURNING id,name',[String(id),String(ownerUserId)]);if(!row)fail('notFound',404);return {ok:true,...row};
}
async function voteTopServer(id,ip,userAgent,userId=''){
 const server=await db.one('SELECT id FROM shared_top_servers WHERE id=$1 AND enabled=TRUE',[id]);if(!server)fail('notFound',404);
 const voter=userId?sha('discord:'+String(userId)):sha(`${ip||'unknown'}|${userAgent||''}`);
 const bucket=Math.floor(Date.now()/7200000);
 const row=await db.one('INSERT INTO shared_top_server_votes(server_id,voter_hash,vote_bucket) VALUES($1,$2,$3) ON CONFLICT(server_id,voter_hash,vote_bucket) DO NOTHING RETURNING id',[id,voter,bucket]);
 const count=await db.one("SELECT COUNT(*)::int AS votes,COUNT(*) FILTER (WHERE created_at>=date_trunc('month',NOW()))::int AS votes_month,COUNT(*) FILTER (WHERE created_at>=NOW()-INTERVAL '24 hours')::int AS votes_24h FROM shared_top_server_votes WHERE server_id=$1",[id]);
 return {accepted:Boolean(row),cooldownSeconds:row?0:Math.max(1,Math.ceil(((bucket+1)*7200000-Date.now())/1000)),...count};
}
async function visitTopServer(id,ip,userAgent){
 const server=await db.one('SELECT id FROM shared_top_servers WHERE id=$1 AND enabled=TRUE',[id]);if(!server)fail('notFound',404);
 const visitor=sha(`${ip||'unknown'}|${userAgent||''}`),bucket=Math.floor(Date.now()/3600000);
 const row=await db.one('INSERT INTO shared_top_server_visits(server_id,visitor_hash,visit_bucket) VALUES($1,$2,$3) ON CONFLICT(server_id,visitor_hash,visit_bucket) DO NOTHING RETURNING id',[id,visitor,bucket]);
 return {accepted:Boolean(row)};
}

async function playMiniGame(g,user,game,answer){if(!['dinoquiz','survivor'].includes(game))fail('invalidInput',400);const questions={dinoquiz:{q:'Quel dinosaure est connu pour sa vitesse et sa chasse en meute ?',a:'raptor'},survivor:{q:'Quel outil permet de récolter efficacement la pierre au début ?',a:'pioche'}};if(answer===undefined)return {game,question:questions[game].q};const correct=String(answer).trim().toLowerCase()===questions[game].a,reward=correct?50:0;await db.query('INSERT INTO ark_minigame_scores(guild_id,user_id,game,score,reward) VALUES($1,$2,$3,$4,$5)',[g,user,game,correct?1:0,reward]);if(reward){await db.query('INSERT INTO ark_wallets(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[g,user]);await db.query('UPDATE ark_wallets SET balance=balance+$3 WHERE guild_id=$1 AND user_id=$2',[g,user,reward]);await db.query('INSERT INTO ark_wallet_transactions(guild_id,user_id,amount,kind,details) VALUES($1,$2,$3,$4,$5)',[g,user,reward,'minigame',{game}])}return {correct,reward}}
module.exports={sha,periodKey,guild,member,active,seasonInGuild,createSeason,publishSeason,archiveSeason,createQuest,createReward,quests,pass,claimQuest,reviewClaim,claimReward,deliverReward,openTicket,ticket,ticketMessage,closeTicket,updateMember,ingest,rawLogs,snapshot,audit,economy,saveRpProfile,transferCredits,grantCredits,addShopItem,buyShopItem,lotteryTicket,drawLottery,playMiniGame,topServers,topServerById,saveTopServer,ownerTopServers,updateTopServer,deleteTopServer,voteTopServer,visitTopServer};
